# Generated by Django 3.0.7 on 2020-06-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='street',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='client',
            name='inactive',
            field=models.BooleanField(default=False, help_text='Mark old clients inactive to keep data w/out deleting'),
        ),
        migrations.AddField(
            model_name='client',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Deliver email/sms notifications to users associated with this client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='The name of this client', max_length=100),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
